nameOverride: ""
fullnameOverride: ""

prometheus:
  image:
    repository: prom/prometheus
    tag: v2.53.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9090
    nodePort: null
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 768Mi
  retention: 24h
  scrapeInterval: 15s
  backendPodScrape:
    enabled: true
    appNameLabel: service-desk-backend
    containerPort: "8000"
  backendTarget: service-desk-backend.service-desk.svc.cluster.local:8000

grafana:
  image:
    repository: grafana/grafana
    tag: 11.1.4
    pullPolicy: IfNotPresent
  adminUser: admin
  adminPassword: admin
  service:
    type: NodePort
    port: 3000
    nodePort: 30300
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
