"""add new field

Revision ID: ad466f629331
Revises: 0002
Create Date: 2026-02-25 22:50:47.656073
"""

from alembic import op
import sqlalchemy as sa


revision = "ad466f629331"
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
