image:
  repository: docker.io/aliquis21/service-desk-backend
  tag: 85b3ddee78f4927e4560a3e3d37529c162c6e045

imagePullSecrets: []

env:
  APP_ENV: "prod"
  UVICORN_RELOAD: "0"
  RUN_MIGRATIONS: "1"
  POSTGRES_HOST: "service-desk-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "service_desk"
  POSTGRES_USER: "service_desk"

existingSecretName: "service-desk-backend-env"
