image:
  repository: docker.io/aliquis21/service-desk-backend
  tag: c8f94b5c505f3f701e056d9fda17d3e3a8452e75

imagePullSecrets: []

env:
  APP_ENV: "prod"
  UVICORN_RELOAD: "0"
  RUN_MIGRATIONS: "1"
  POSTGRES_HOST: "service-desk-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "service_desk"
  POSTGRES_USER: "service_desk"

existingSecretName: "service-desk-backend-env"
