image:
  repository: docker.io/aliquis21/service-desk-backend
  tag: 79ef601c4f8e268a0ea3d23c5ec8107c6001ad85

imagePullSecrets: []

env:
  APP_ENV: "prod"
  UVICORN_RELOAD: "0"
  RUN_MIGRATIONS: "1"
  POSTGRES_HOST: "service-desk-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "service_desk"
  POSTGRES_USER: "service_desk"

existingSecretName: "service-desk-backend-env"
