apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-desk-root
  namespace: argocd
spec:
  project: service-desk
  source:
    repoURL: https://github.com/entozhevlad/service-desk.git
    targetRevision: lab-4-fix-3
    path: argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
