apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-desk-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: service-desk
  source:
    repoURL: https://github.com/entozhevlad/service-desk.git
    targetRevision: lab-4-argocd-fix
    path: helm/service-desk-monitoring
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: service-desk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
