apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-desk-frontend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: service-desk
  source:
    repoURL: https://github.com/entozhevlad/service-desk.git
    targetRevision: main
    path: helm/service-desk-frontend
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: service-desk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
