apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-desk-monitoring.grafanaName" . }}-admin
  labels:
    {{- include "service-desk-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.adminUser | quote }}
  admin-password: {{ .Values.grafana.adminPassword | quote }}
