apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service-desk-monitoring.prometheusServiceAccountName" . }}
  labels:
    {{- include "service-desk-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
