apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "service-desk-monitoring.prometheusName" . }}
  labels:
    {{- include "service-desk-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
