image:
  repository: aliquis21/service-desk-frontend
  tag: 1da99939f792fc9acbb3f78317eff27585a6a3ad

backend:
  serviceName: service-desk-backend
  servicePort: 8000

service:
  type: NodePort
  port: 80
  nodePort: 30081
