image:
  repository: aliquis21/service-desk-frontend
  tag: 24224c71e0d8decd1da43e43d895d3e87dd2c283

backend:
  serviceName: service-desk-backend
  servicePort: 8000

service:
  type: NodePort
  port: 80
  nodePort: 30081
