image:
  repository: aliquis21/service-desk-frontend
  tag: c8f94b5c505f3f701e056d9fda17d3e3a8452e75

backend:
  serviceName: service-desk-backend
  servicePort: 8000

service:
  type: NodePort
  port: 80
  nodePort: 30081
